config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root to: 'lists#index'

  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
authenticate :user, lambda { |u| u.admin? } do
  mount Sidekiq::Web => '/sidekiq'

  namespace :madmin do
  end
end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  resources :cards do
    member do
      patch :move
    end
  end
  
  resources :lists do
    member do
      patch :move
    end
  end
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :list

  validates :name, presence: true

  acts_as_list scope: :list
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: %i[ show edit update destroy move]

  def index
    @cards = Card.all
  end

  def show
  end

  def new
    @card = Card.new
  end

  def edit
  end

  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        ActionCable.server.broadcast "board", { commit: 'addCard', payload: render_to_string(:show, formats: [:json]) }
        format.json { render :show, status: :created, location: @card }
      else
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @card.update(card_params)
        ActionCable.server.broadcast "board", { commit: 'editCard', payload: render_to_string(:show, formats: [:json]) }
        format.json { render :show, status: :ok, location: @card }
      else
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @card.destroy
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  def move
  @card.update(card_params)
    render action: :show
  end

  private
    def set_card
      @card = Card.find(params[:id])
    end

    def card_params
      params.require(:card).permit(:list_id, :name, :position)
    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_form.html.erb
<%= form_with(model: card, local: true) do |form| %>
  <% if card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :list_id, class: 'form-label' %>
    <%= form.text_field :list_id, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :name, class: 'form-label' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :position, class: 'form-label' %>
    <%= form.number_field :position, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <% if card.persisted? %>
      <div class="float-right">
        <%= link_to 'Destroy', card, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

    <%= form.submit class: 'btn btn-primary' %>

    <% if card.persisted? %>
      <%= link_to "Cancel", card, class: "btn btn-link" %>
    <% else %>
      <%= link_to "Cancel", cards_path, class: "btn btn-link" %>
    <% end %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Edit Card</h1>

<%= render 'form', card: @card %>

app/views/cards/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Cards</h1>
  </div>

  <div class="col-sm-6 text-right">
  <%= link_to new_card_path, class: 'btn btn-primary' do %>
    Add New Card
  <% end %>
  </div>
</div><hr>

app/views/cards/new.html.erb
<h1>New card</h1>

<%= render 'form', card: @card %>

app/views/cards/show.html.erb
<div class="page-header">
  <%= link_to cards_path, class: 'btn btn-default' do %>
    All Cards
  <% end %>
  <%= link_to edit_card_path(@card), class: 'btn btn-primary' do %>
    Edit
  <% end %>
  <h1>Show card</h1>
</div>

<dl class="dl-horizontal">
  <dt>List:</dt>
  <dd><%= @card.list %></dd>
  <dt>Name:</dt>
  <dd><%= @card.name %></dd>
  <dt>Position:</dt>
  <dd><%= @card.position %></dd>
</dl>